variable "cluster_name" {}
variable "env" {}
variable "engine" {}
variable "node_type" {}
variable "cache_nodes" {}
variable "engine_version" {}
variable "parameter_group" {}
variable "subnet_group" {}
variable "db_subnet_ids" {}
